; this is an INI file
[pg]
error_reporting = E_ALL | E_STRICT
log_errors = On
display_errors = Off
error_log = /kunden/homepages/26/d169250974/htdocs/www/courses/log/php-errors.log
mail.log = /kunden/homepages/26/d169250974/htdocs/www/courses/log/mail.log
date.timezone = 'Europe/Paris'
upload_max_filesize = 20M
